# This file was generated by GoReleaser. DO NOT EDIT.
cask "athenaeum" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "59feb31d3cd7527a6543f159c651fc67c20bdc20237bc8350be5fc8a09d3302f"
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v#{version}/athenaeum_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a756309b20d25f980e09fabf9a95f96a5e4dda02e8bacc64e1cdfaa49ee6bf00"
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v#{version}/athenaeum_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "62ee4a3bef1230a392aebd847b25769f12ccc438859d294ab82e0b4c53e781c0"
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v#{version}/athenaeum_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "48ab945b1a243be71021592703e323397ed87926652dbef609df8b74cfa38cee"
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v#{version}/athenaeum_#{version}_linux_arm64.tar.gz"
    end
  end

  name "athenaeum"
  desc ""
  homepage "https://github.com/CallumKerson/Athenaeum"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "athenaeum"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/athenaeum"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ****************************************************************
    Athenaeum generates a static site. Run `athenaeum build` to
    regenerate it, and serve the output directory with a web server.
    Configuration lives at ~/.config/athenaeum/athenaeum.toml
    ****************************************************************
  EOS
end
