# This file was generated by GoReleaser. DO NOT EDIT.
cask "athenaeum" do
  version "2.2.0"

  on_macos do
    on_arm do
      sha256 "f51bf5ca53bd88ec45ce186ebbe0b1bd49de2a50e2edaabdcb19867b06dc2bf5"
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v#{version}/athenaeum_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a6555198f27255da3db42d69f985f624efb7291b5614202ce19d7f44cb5efacd"
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v#{version}/athenaeum_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "06857f687a1193ff0ccf0ca1fb0acab72dea510a35e2547eb34d8ced281876ac"
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v#{version}/athenaeum_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3e8bb5719bb98f14a4553555d7cea270b3d48cfdca36eca432ff61bd8c97750d"
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v#{version}/athenaeum_#{version}_linux_amd64.tar.gz"
    end
  end

  name "athenaeum"
  desc ""
  homepage "https://github.com/CallumKerson/Athenaeum"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "athenaeum"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/athenaeum"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ****************************************************************
    Athenaeum generates a static site. Run `athenaeum build` to
    regenerate it, and serve the output directory with a web server.
    Configuration lives at ~/.config/athenaeum/athenaeum.toml
    ****************************************************************
  EOS
end
