# This file was generated by GoReleaser. DO NOT EDIT.
cask "athenaeum" do
  version "2.0.1"

  on_macos do
    on_intel do
      sha256 "9f605ab642da9b7e09ac752ffc440361013fb5bdd5538935192f0987250b4826"
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v#{version}/athenaeum_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6f57abde099432aa8140990b145f926d7a8722a12cd87f90ae4407d1e12156df"
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v#{version}/athenaeum_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cbb4be74c56780df012ca80841dc4e4f8efab3aaee843baf78661515bd22acfb"
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v#{version}/athenaeum_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "442456d0989a90fa9f6263f5a2721bee987348570bc5a82dc4d268819e239c36"
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v#{version}/athenaeum_#{version}_linux_arm64.tar.gz"
    end
  end

  name "athenaeum"
  desc ""
  homepage "https://github.com/CallumKerson/Athenaeum"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "athenaeum"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/athenaeum"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ****************************************************************
    Athenaeum generates a static site. Run `athenaeum build` to
    regenerate it, and serve the output directory with a web server.
    Configuration lives at ~/.config/athenaeum/athenaeum.toml
    ****************************************************************
  EOS
end
