# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Athenaeum < Formula
  desc ""
  homepage "https://github.com/CallumKerson/Athenaeum"
  version "1.6.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v1.6.3/athenaeum_1.6.3_darwin_arm64.tar.gz"
      sha256 "4059757f79f2d4b5a2eb4ad930d03d6b3f3975e0bbb7039d8643b13409c6f145"

      def install
        bin.install "athenaeum"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v1.6.3/athenaeum_1.6.3_darwin_amd64.tar.gz"
      sha256 "7fd77e07c1a4d072d542b38219c54fee16a6f164f03ccb65b8eb5ae7f9ba10a1"

      def install
        bin.install "athenaeum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v1.6.3/athenaeum_1.6.3_linux_arm64.tar.gz"
      sha256 "9d035888c409b69fc0e9ca4957d4a834645531476876df9712a62ab65ec7805a"

      def install
        bin.install "athenaeum"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/CallumKerson/Athenaeum/releases/download/v1.6.3/athenaeum_1.6.3_linux_amd64.tar.gz"
      sha256 "26805bee644e3c44162070a12d53e67794d034f5ccf584a38893fc937bfe6639"

      def install
        bin.install "athenaeum"
      end
    end
  end

  def caveats
    <<~EOS
      ****************************************************************
      Below are services commands to run to manage the athenaeum service.
      If you wish to run the athenaeum at boot prefix these commands with sudo
      otherwise the service will run at login.
      To start the athenaeum service run:
        brew services start CallumKerson/homebrew-tap/athenaeum
      To stop the athenaeum service run:
        brew services stop CallumKerson/homebrew-tap/athenaeum
      To restart the athenaeum service run:
        brew services restart CallumKerson/homebrew-tap/athenaeum
      ****************************************************************
    EOS
  end

  service do
    run [opt_bin/"athenaeum", "run" ,"--config", etc/"athenaeum.yaml"]
    environment_variables ATHENAEUM_DB_ROOT var/"athenaeum"
    keep_alive true
    error_log_path var/"log/athenaeum.log"
    log_path var/"log/athenaeum.log"
  end

  test do
    system "#{bin}/athenaeum --version"
  end
end
